services:
  - type: web
    name: eventii-management-platform
    env: node
    buildCommand: npm install && npm run build-frontend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        sync: false
    healthCheckPath: /health
